language: java
jdk: oraclejdk7

before_install:
    - wget http://dl.google.com/android/android-sdk_r21.1-linux.tgz
    - tar -zxf android-sdk_r21.1-linux.tgz
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    - android update sdk --filter platform-tools,android-16 --no-ui
    - chmod +x gradlew